version: '2'
services:
  passapi1:
    image: nicopaez/password-api:2.1.0
  passapi2:
    image: nicopaez/password-api:2.1.0
  balanceador:
    image: nginx:1.13
    volumes: 
        - './site.conf:/etc/nginx/conf.d/site.conf'    
    ports:
      - "3000:3000"
    depends_on:
      - passapi1
      - passapi2