apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot
  labels:
    app: telegrambot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegrambot
  template:
    metadata:
      labels:
        app: telegrambot
    spec:
      containers:
      - name: telegrambot
        image: nicopaez/telegrambot:0.0.7
        env:
        - name: TELEGRAM_TOKEN
          value: 5712600111:AAHB-pbH2Qc5W8jstG9g6A25LJcPN7DYtJs